### ISSUE TITLE
Assignment to undeclared variable s_argument

### ISSUE THREAD

**Issue by ezranuite** [nrk/redis-lua#17]
When strict is enabled an error is encountered in redis.lua on line 334.

redis.lua:334: assign to undeclared variable 's_argument'

**Comment by ezranuite** [comment]
It looks like this has been fixed in code, but the luarock 2.0.3-1 still contains the error.

**Comment by nrk** [comment]
Yes these kind of errors have been fixed in the current development version for v2.0.4 but it will take a few more days before tagging the new release (and a couple of new commands have been added in Redis 2.6 yesterday, I'm going to add them).

I will close this issue when the new version of redis-lua will be available, in the meanwhile you should be able to use the code from the `version-2.0` branch since it is stable enough even for production use.

Thanks for reporting the issue!

**Comment by nrk** [comment]
I'm closing this issue since redis-lua v2.0.4 has been finally released. Thanks!
