### ISSUE TITLE
Redis 2.0+ Support

### ISSUE THREAD

**Issue by gottlike** [nrk/redis-lua#3]
It would be super nice if redis-lua development would keep up-to-date (more or less) with current Redis development.

Redis 2.0 is officially stable now and antirez strongly encourages the use of Redis 2.0 instead of 1.2.

**Comment by nrk** [comment]
I know I'm a bit behind my schedule with redis-lua but support for Redis 2.0 is currently being developed in a [separate branch](http://github.com/nrk/redis-lua/tree/dev) and it is actually quite ready, what's missing right now before going on with a full release is a more friendly abstraction for MULTI / EXEC contexts similar to the approach used for command pipelining and just a few minor changes.

This will also mark the release of redis-lua 2.0.0 since it contains quite a few breaking changes with the 1.x series, but now the library is definitely better and more robust than before. That said, the _dev_ branch is pretty much stable now and you should be able to use it without problems. If you do, feedback would be appreciated.

Thanks,
Daniele

**Comment by gottlike** [comment]
Very nice! I'll probably rely on your library in a future project (Nginx + Lua(JIT)-Plugin + Redis), so your work on this update is very much appreciated!

Thanks a lot for redis-lua :-),
Dustin

**Comment by nrk** [comment]
I'm closing this issue since redis-lua 2.0.0 has finally been released with full support for Redis 2.0 and 2.2-dev.

Thanks,
Daniele

**Comment by gottlike** [comment]
Great! Thanks a lot.
