### ISSUE TITLE
Support for Unix Sockets

### ISSUE THREAD

**Issue by catwell** [nrk/redis-lua#8]
I might have overlooked something but I think redis-lua doesn't support Unix Sockets. Do you think it would be possible to add support for them?

**Comment by nrk** [comment]
That's right, redis-lua doesn't support unix domain sockets right now. The reason is pretty simple: LuaSocket, on top of  which redis-lua is built, doesn't provide support for them (or, better said, it doesn't support them by default). I will look into this later, I was already going to release a new patch release of redis-lua later this week so the timing for your request is perfect :-)

**Comment by catwell** [comment]
Great, thanks!

**Comment by nrk** [comment]
It's been quite easy to get a first hacked version of redis-lua working with unix sockets, I just need to polish things a bit before pushing the code on the repository. The only downside of the story is that you have to manually apply a couple of changes to the makefile of LuaSocket to enable `unix.c` and thus the needed support for unix domain socket :-(

**Comment by nrk** [comment]
Implemented with [commit 3c5a1ab](http://github.com/nrk/redis-lua/commit/3c5a1abe8e478a802fd906bba14600ce064864c9).

Keep in mind that you must have a build of LuaSocket that supports UNIX domain sockets to get them working with redis-lua. This can be obtained by modifying [this line of a makefile](http://github.com/LuaDist/luasocket/blob/2.0.2/src/makefile#L50) of LuaSocket in order to include `$(UNIX_SO)`.
